clang: pasTropDOptim
# Le clang 3.4.6 système livré avec FreeBSD plante les compils en -O3. On s'adapte.

darcs-hash:33334fc89a2b1bd48e3dfe17f2e3bfde2db37399

diff --git a/llvm b/llvm
--- a/llvm
+++ b/llvm
@@ -32,16 +32,16 @@ Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2"
 # Attention, quand on a déjà un llvm-3.9.1 d'installé, et qu'on essaie de compiler un llvm+clang 3.9.1, pour je ne sais quelle raison, seul le llvm se compile, argh.
 
 v 3.3 || true
-v 3.4.2 && modifs="macMath stdcppPasTropEnDur sansOcaml" || true # Ne compile pas avec gcc 4.7.4 (même erreur que https://bugs.gentoo.org/show_bug.cgi?id=515882)
-v 3.5.0 && modifs="macMath strtoll stdcppPasTropEnDur sansOcaml" || true # A un petit problème avec strtoll.
+v 3.4.2 && modifs="pasTropOptim macMath stdcppPasTropEnDur sansOcaml" || true # Ne compile pas avec gcc 4.7.4 (même erreur que https://bugs.gentoo.org/show_bug.cgi?id=515882)
+v 3.5.0 && modifs="$modifs strtoll" || true # A un petit problème avec strtoll.
 v 3.5.2 || true
-v 3.6.0 && modifs="macMath strtoll stdcppPasTropEnDur sansOcaml sansCodecvt pathMax ocloexec gccframework complications" && prerequis="swig \\ " || true
+v 3.6.0 && modifs="$modifs sansCodecvt pathMax ocloexec gccframework complications" && prerequis="swig \\ " || true
 v 3.6.2 || true
-v 3.7.1 && modifs="macMath ocloexec alignementBiblios" && prerequis="make python >= 2.7 \\" || true
+v 3.7.1 && modifs="pasTropOptim macMath ocloexec alignementBiblios" && prerequis="make python >= 2.7 \\" || true
 # cmake: pour un clang 5.0.2, cmake 3.13.1 nous pète en "do not use OLD behavior, puis core dumped". Le 3.5 passe.
 # Humph, quelques années plus tard rebelote, mais le 3.5 pète aussi (sur une autre alerte, ĉ quoi /usr/local/lib/libexecinfo.so masque celui d'/usr/lib, mais le principe est le même: sur alerte, core dump).
 # Il semble que ça soit surtout le "je désinstalle le clang récent auquel cmake s'est lié, pour recompiler un vieux clang" qui joue: en recompilant un cmake avec le clang système, ça passe.
-v 3.9.1 && modifsDyn="macMath macLibtool unwind" && modifs="$modifsDyn llvmStrnlen" && prerequis="cmake < 3.10 \\" && OPTIONS_CMAKE="-DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON" || true # build external machin: https://www.bountysource.com/issues/29603185-compiler-rt-is-built-with-the-wrong-toolchain-bootstrap-compiler-rather-than-built-clang-linking-fails-when-using-clang-older-than-3-5-eg-mavericks-and-earlier-xcodes. Ne sera plus valable en 4.0 et suivants.
+v 3.9.1 && modifsDyn="pasTropOptim macMath macLibtool unwind" && modifs="$modifsDyn llvmStrnlen" && prerequis="cmake < 3.10 \\" && OPTIONS_CMAKE="-DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON" || true # build external machin: https://www.bountysource.com/issues/29603185-compiler-rt-is-built-with-the-wrong-toolchain-bootstrap-compiler-rather-than-built-clang-linking-fails-when-using-clang-older-than-3-5-eg-mavericks-and-earlier-xcodes. Ne sera plus valable en 4.0 et suivants.
 v 4.0.0 || true
 v 4.0.1 || true
 v 5.0.0 || true
@@ -105,6 +105,21 @@ pge $version 3.5 || suffixe=gz
 archive="`archive llvm`"
 
 # Modifs.
+
+pasTropOptim()
+{
+	# Certains vieux BSD ont un clang++ qui plante en -O3
+	case "`command -v "$CXX" 2> /dev/null || true`" in
+		"$INSTALLS"/*) return ;; # Si c'est un à nous on l'estime bien compilé.
+	esac
+	case "`uname`" in
+		FreeBSD) true ;;
+		*) return ;;
+	esac
+	export CXXFLAGS="`printf %s "$CXXFLAGS" | sed -e 's/-O3/-O1/g'`"
+	export CFLAGS="`printf %s "$CFLAGS" | sed -e 's/-O3/-O1/g'`"
+	livrable=Debug
+}
 
 trouverBiblio()
 {
@@ -366,6 +381,8 @@ integrer projects/libcxx      libcxx
 modulesClang
 fi
 
+livrable=Release
+
 echo Correction… >&2
 for modif in true $modifs ; do $modif ; done
 
@@ -388,7 +405,7 @@ then
 		-DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
 		-DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS" \
 		-DCMAKE_MODULE_LINKER_FLAGS="$LDFLAGS" \
-		-DCMAKE_BUILD_TYPE=Release \
+		-DCMAKE_BUILD_TYPE=$livrable \
 		$OPTIONS_CMAKE \
 		..
 else
